# Generated by Django 6.0.4 on 2026-04-19 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['symbol'], 'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AlterModelOptions(
            name='marketnews',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новость рынка', 'verbose_name_plural': 'Новости рынка'},
        ),
        migrations.AlterModelOptions(
            name='pricedata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Данные о цене', 'verbose_name_plural': 'Данные о ценах'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['name'], 'verbose_name': 'Список наблюдения', 'verbose_name_plural': 'Списки наблюдения'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Акция'), ('FOREX', 'Форекс'), ('CRYPTO', 'Криптовалюта'), ('COMMODITY', 'Товар'), ('INDEX', 'Индекс')], max_length=20, verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20, unique=True, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='related_assets',
            field=models.ManyToManyField(blank=True, related_name='news', to='markets.asset', verbose_name='Связанные активы'),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='source',
            field=models.CharField(max_length=200, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='markets.asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='close_price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена закрытия'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='high_price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Максимальная цена'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='low_price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='open_price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена открытия'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='volume',
            field=models.BigIntegerField(default=0, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='assets',
            field=models.ManyToManyField(related_name='watchlists', to='markets.asset', verbose_name='Активы'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
